#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.ftl

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  freemarker:
    request-context-attribute: req
    suffix: .ftl
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      number_format: